### ISSUE TITLE
Text not visible on confirmation email button [bz1246080]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#128]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1246080

Created attachment 8716185
Screen Shot 2016-02-05 at 11.27.11 AM.png

Step to reproduce : 

Open a new Sync Account. Go to verification mail. 

Actual Result 

Button text is not visible clearly. 

Expected Result 

Button text should be visible.

**Comment by shane-tomlinson** [comment]
The reporter mentioned zoho mail. I use zoho mail. I confirm this is a problem:

![screen shot 2016-02-10 at 09 13 42](https://cloud.githubusercontent.com/assets/848085/12943049/9b8f3102-cfd6-11e5-9434-85e632326315.png)

**Comment by shane-tomlinson** [comment]
If you look closely, "Activate now" is there, it's just very difficult to see because zoho adds their own style to links.

We add text color styling to the containing `td` element, but not the link itself. Zoho uses CSS to style the link. We should override Zoho's styles by providing styles on the link itself.

![screen shot 2016-02-10 at 09 15 20](https://cloud.githubusercontent.com/assets/848085/12943115/fe08474c-cfd6-11e5-82df-106375888dc9.png)

**Comment by shane-tomlinson** [comment]
Opened https://github.com/mozilla/fxa-auth-mailer/issues/119, closing here.
