### ISSUE TITLE
User is still able to manage the Firefox account, even after logging out [bz1265340]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#150]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1265340

[Affected versions]:
- 48.0a1 (2016-04-17)
- 47.0a2 (2016-04-18)
- 46.0b11 build1 (20160414152344)
- 45.0.2 build1 (20160407164938)
- 44.0 build3 (20160123151951)
- 29.0

[Affected platforms]:
- Windows 10 x64 
- Mac OS X 10.11 
- Ubuntu 14.04 x86 

[Steps to reproduce]:
1. Launch Firefox with a new profile.
2. Go to Hamburger Menu > Sign in to Sync and click the Sign In button from the Connect with a Firefox Account section.
3. In the Firefox Sync page, enter the credentials for a valid Firefox account and click the Sign In button.
4. In the Firefox Account section from the same page (Options), click the Manage Account link. 
5. Move to the Options page in order to access again the Firefox Account section then click the Disconnect and the Continue buttons.
6. Go to the last opened tab (Firefox Accounts page) and try to modify the account information (Account picture, Display name, etc.) by accessing the corresponding buttons.

[Expected result]:
- After step 5, the user is successfully disconnected from the Firefox account on every active Firefox tab/window.

[Actual result]:
- The user is still able to manage the Firefox account, even after logging out.

[Regression range]:
- This issue is _not a regression_, as it's reproducible all the way back to Fx29.0.
- Please note that I'm setting this bug's severity as [major] because it might be considered as a privacy issue as well.

**Comment by vladikoff** [comment]
@vladikoff and @shane-tomlinson will discuss this bug ...

**Comment by shane-tomlinson** [comment]
The core problem is that Firefox destroys the session and it's oauth tokens, but the content server does not find out this information. The browser does not notify any open content server windows, and the content server does not check.

Here are several (most not very good) ideas:

1. Disallow signout from within the browser. Move signout to Firefox Accounts. This will be a bad experience for older browsers.
1. Have FxA subscribe to push notifications, send a notification on signout. When the notification occurs, sign out the user.
1. When the user clicks "Disconnect" and "continue" in the browser, send an unsolicited WebChannel message to any open FxA windows. Open FxA windows will do the right thing.
1. A content-server code only fix is to use a fresh profile server OAuth token for *EACH OPERATION*. Since the user's session will be invalid, they will be unable to fetch a new OAuth code/token.
1. Another content-server code only fix is to check the user's session status before each operation. We'll find out the session was destroyed and take the appropriate action.

**Comment by shane-tomlinson** [comment]
> The core problem is that Firefox destroys the session and it's oauth tokens, 

The plot thickens. This isn't always so. In Fx 47, when the user clicks "Disconnect", the user's FxA session is destroyed. In Fx 50, this behavior has changed so that the user's FxA session is *still valid*. Both Fx 47 and Fx 50 call /account/device/destroy, so I'm unsure what's going on. @philbooth is attempting to debug at the moment.

**Comment by vladikoff** [comment]
@shane-tomlinson is still active?
