### ISSUE TITLE
"Missing or duplicate items?" link in device manager has no advice for duplicate items [bz1314475]

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-bugzilla-mirror#197]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1314475

The new device view has a link with the text "Missing or duplicate items?" which opens https://support.mozilla.org/en-US/kb/fxa-managing-devices?utm_source=accounts.firefox.com&utm_medium=referral&utm_campaign=fxa-devices - however, that page has no advice for duplicate items, only for missing items.

**Comment by ryanfeeley** [comment]
Looking at GA, it appears as though that link has had 6,252 hit to 3,263 users since it started. fxa.content.screen.settings.clients value is returning 19,947 hits. If that's only sampling at 10%, then we can estimate that 1.6% of users are clicking the link, which is pretty good. We should be keeping an eye on this number somehow.

I'm not sure what kind of device we should offer when there are duplicates, although I would like us to stay alert for spikes on this number.

**Comment by vladikoff** [comment]
We provided the content for SUMO to add to the existing article.
