### ISSUE TITLE
"Unexpected error" message is displayed when user changes preferences in Communication area [bz1336099]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#238]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1336099

Environment: 
Device: Motorola Nexus 6 (Android 6.0.1);
Build: Nightly 54.0a1 (2017-02-01);

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings (the user must be signed in);
2. Tap Change button from the Communication preferences area;
3. Tap on the Subscribe button;
4. Tap Change button from the Communication preferences area;
5. Tap the Unsubscribe button;
6. Tap Change button from the Communication preferences area;
7. Tap on the Subscribe button;

Expected result:
The message "Unexpected error" is displayed.

Actual result:
Subscribed successfully message is displayed.

Notes:
Reproducible also on wind 7 and 10, and on iPad Air 2 iOS 10.

**Comment by vladikoff** [comment]
Confirmed: ![](http://v14d.com/i/589ca9376dbe4.jpg)

**Comment by shane-tomlinson** [comment]
@vladikoff reports that the action is being rate-limited and returning a 429. We should tell the user they are a bit quick with the mouse clicks.

**Comment by heatherbooker** [comment]
Hi! I'd like to work on this bug.

So to me, one unsubscribe seems a little stingy! Perhaps two is a little more generous without allowing unnecessary load on the system? It looks like it's controlled in [basket](https://github.com/mozmar/basket/blob/56fdb5217702634f8b0d2294ff1ab62fe874c78c/news/views.py#L60):

```python
# one submission for a specific message per phone number per 10 minutes
PHONE_NUMBER_RATE_LIMIT = getattr(settings, 'PHONE_NUMBER_RATE_LIMIT', '1/10m')
# one submission for a set of newsletters per email address per 10 minutes
EMAIL_SUBSCRIBE_RATE_LIMIT = getattr(settings, 'EMAIL_SUBSCRIBE_RATE_LIMIT', '1/10m')
```

If it's possible to make this 2/10m, or even 2/20m or something along those lines, I'm happy to also submit an issue/PR in that repo, as well as still adding a notice if users are rate-limited telling them to try again later.

**Comment by vladikoff** [comment]
@heatherbooker hello, yeah we can tweak that. However, we need to add the error handler in this repo. See the "rate limit" message above. if we get that as a response we need to say something like "Please try again later" instead of Unexpected error

**Comment by heatherbooker** [comment]
I'm having some difficulty solving this, any help would be greatly appreciated! :)

First is that if I run the server locally with `npm run start-remote`, then when I click the subscribe button I get a "System unavailable, try again soon". If I run `./pm2 start servers.json` from the root fxa dir, I can sub and unsub to my heart's content with no errors - I guess that's because basket-proxy is using basket/fake.js? So I'm not sure how to test this.

The other issue (which is basically the entire issue I think? ha.) is identifying where this message should come from - should I add a RATE_LIMIT_REACHED error with errno: 429 to [app/scripts/lib/marketing-emails.js](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/marketing-email-errors.js)? I'm just finding it really hard to trace the source of the error and at what point it is being assigned the string 'Unexpected error'.

Thanks in advance and sorry for any inconvenience! ><

**Comment by vladikoff** [comment]
@heatherbooker 

> First is that if I run the server locally with npm run start-remote, then when I click the subscribe button I get a "System unavailable, try again soon". 

Ah this is probably because we don't have the basket proxy stuff running in that environment. No worries though, see below. 

>  If I run ./pm2 start servers.json from the root fxa dir, I can sub and unsub to my heart's content with no errors - I guess that's because basket-proxy is using basket/fake.js? So I'm not sure how to test this.

Modify this code: https://github.com/mozilla/fxa-basket-proxy/blob/master/lib/basket/fake.js#L93 and restart the basket proxy. For testing purposes make it return `res.status(429).json({ status: 'error', ... });` (see screenshot above for full response)

We already have a handler for `errno: 5` here: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/marketing-email-errors.js#L40 See if changing the message string there from `UNEXPECTED_ERROR` to a `t('Please try again later')` fixes the problem. 

If not then add an error handler here: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/communication_preferences.js#L110

Just like in these examples of handling / converting errors: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings/communication_preferences.js#L50 

And make it say `Please try again later` instead of `Unexpected error`

**Comment by vladikoff** [comment]
@heatherbooker finally, add a unit test for the `setOptInStatus` where `getMarketingEmailPrefs` throws an error with 429. Example: https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/settings/communication_preferences.js#L222

**Comment by vladikoff** [comment]
@heatherbooker you can run unit tests by going to 127.0.0.1:3030/tests/index.html (there is also grep to help just run one test, example: 127.0.0.1:3030/tests/index.html?grep=destroyAccountSession )

**Comment by heatherbooker** [comment]
@vladikoff Thank you for the pointers - I just opened a [PR](https://github.com/mozilla/fxa-content-server/pull/4812) with the changes, let me know if anything should be changed.
