### ISSUE TITLE
"Error: Unverified session" trying to deactive 2 factor [bz1473493]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#533]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1473493

opened firefox settings
clicked manage account
tried to deactive 2 factor

https://api.accounts.firefox.com/v1/totp/destroy

POST /v1/totp/destroy HTTP/1.1
Host: api.accounts.firefox.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: */*
Accept-Language: da,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://accounts.firefox.com/
authorization: Hawk id="XXXX", ts="XXXX", nonce="XXXX", hash="XXXX", mac="XXXX"
Content-Type: application/json
Content-Length: 2
Origin: https://accounts.firefox.com
DNT: 1
Connection: keep-alive

HTTP/1.1 400 Bad Request
access-control-allow-origin: https://accounts.firefox.com
access-control-expose-headers: WWW-Authenticate,Server-Authorization,Timestamp,Accept-Language
cache-control: no-cache
content-encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 05 Jul 2018 08:18:44 GMT
Public-Key-Pins: pin-sha256="XXXX"; pin-sha256="XXXX"; max-age=5184000; includeSubdomains
strict-transport-security: max-age=15552000; includeSubDomains
Timestamp: 1530778724
vary: origin,accept-encoding
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-xss-protection: 1; mode=block
Content-Length: 159
Connection: keep-alive

**Comment by shane-tomlinson** [comment]
cc @vbudhram

**Comment by vbudhram** [comment]
Followed up in the bug, most likely the user is trying to remove from a session that hasn't been verified with a 2FA code.

**Comment by vbudhram** [comment]
We currently have users verify their email (if needed) before seeing this panel. This works fine for adding 2FA, but not to modify it. The ideal solution would be to prompt the user to enter the 2FA code to modify those settings.

**Comment by andrenasturas** [comment]
This issue is now blocking for me, as I have to sync a new computer and my 2FA app is somehow broken for Firefox Sync (I had to wait few seconds after the code prompted before using it, and now it is totally broken, I can't authentificate with 2FA).
Because of this issue, I can't disable 2FA and sync my new computer and re-enable 2FA.
Backup codes link is broken in the same way.

**Comment by shane-tomlinson** [comment]
@andrenasturas The fix for this will be to ask you to enter your 2FA code to disable 2FA. Since it sounds like 2FA is not reliably working for you, the fix won't work. I'm curious, what error message is displayed whenever you type a 2FA code?

When you say the Backup codes link is broken in the same way, can you say more? As in, you click the link and nothing happens, or when you go to the recovery code screen, none of the saved recovery codes work for you?

**Comment by shane-tomlinson** [comment]
For folks frustrated by this problem, here are some possible work arounds:

1. See if you have any devices already connected to Sync. If you do, disable 2FA from one of those devices.
2. If you still have your 2FA device, sign out of Sync and sign in again, entering your 2FA code. You will be able to continue from there.

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa-content-server/issues/6767 which is "in progress", closing.

**Comment by andrenasturas** [comment]
@shane-tomlinson 
> When you say the Backup codes link is broken in the same way, can you say more?

I click the link and nothing happens, and in the console I get the same message "Error: Unverified session". It seems to be the same issue, both backup codes link and disable 2FA button being unavailable if the session is not verified.

> I'm curious, what error message is displayed whenever you type a 2FA code?

"Invalid two-step authentication code", both in console and on the input field.

And I just now successfully synced a new Firefox by getting a 2FA code, waiting 2 minutes (4 new codes were generated since then) and then using it. I was trying the same code several times until it works. I think this may be a complete separate issue that I should open (or find if it exists already). For information, I use Android andOTP as 2FA agent.

I managed to disable 2FA with this newly synced Firefox, so I will be able to sync my new computer fine. However I hope that this unverified session issue will be fixed soon :)

**Comment by shane-tomlinson** [comment]
> > When you say the Backup codes link is broken in the same way, can you say more?
> I click the link and nothing happens, and in the console I get the same message "Error: Unverified session".

cc @vbudhram - can you verify this behavior, seems like there might be something more afoot than we thought.

**Comment by fabiocmg** [comment]
I'm with the same problem. I lost my phone and cant't use 2FA in it. The PCs I had are synced for a long time and it showing the unverified session message. I can't even delete my account.
