### ISSUE TITLE
Issues duplicated prior to being marked Employee Confidential on bugzilla are public here

### ISSUE THREAD

**Issue by abartlet** [mozilla/fxa-bugzilla-mirror#629]
I want to note that #579 is private on bugzilla.mozilla.org but public here.  This might not be a good idea.

**Comment by shane-tomlinson** [comment]
@abartlet thank you, the referenced bug was duplicated by a script before I marked it as Mozilla Employee Confidential due to the bug containing PII. I removed the PII from the bug's description on Feb 8th, I should have closed it then. The script would not have duplicated the issue had the bugzilla bug been marked confidential at the time it was run.

An improvement to the script may be to have the script close and remove the titles/descriptions of Github issues that are marked as Employee Confidential in bugzilla, leaving just a link.

**Comment by clouserw** [comment]
Thanks for bringing this up.  This isn't something we're going to work on for now.
