### ISSUE TITLE
Infinite Loading on the Firefox Accounts page after you want to log in second time [bz1553758]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa-bugzilla-mirror#648]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1553758

**Affected versions**
* Tested on Nightly 69.0a1 (2019-05-22)

**Affected platforms**
* Tested on Mac OS 10.14 and Windows 10 

**Steps to reproduce**
Prerequisites: 
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:

identity.fxaccounts.autoconfig.uri to https://latest.dev.lcip.org/
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://latest.dev.lcip.org/
Restart the browser.

Steps:
1. Log in into your account from the about:welcome page ( I used a verified account)
2. Disconnect your account: Go to avatar icon in the toolbar click on it -> from the dropdown choose Sync settings... and select "Disconnect" -> "Just Disconnect"
3. Try and sing in a second time with the same account from the about:welcome page

**Expected result**
* You need to enter your password 

**Actual result**
* Infinite loading on the Firefox Accounts page

Note: At step 3 you can use any email address valid/invalid and you will see the infinite loading page.

**Comment by clouserw** [comment]
So far we haven't reproduced this

**Comment by shane-tomlinson** [comment]
Bumped this over to the Firefox: Activity Streams: Newtab

What happens is the about:config values populated based on `identity.fxaccounts.autoconfig.uri` are reset whenever the user disconnects from Sync. This causes the browser to expect WebChannel messages from accounts.firefox.com rather than the test server.

As noted in the bug, other parts of the browser seem to get around this by re-populating the fields that are generated from `identity.fxaccounts.autoconfig.uri` every time FxA is loaded.

Closing here.

**Comment by shane-tomlinson** [comment]
### screencap showing the problem

![reset-about-config](https://user-images.githubusercontent.com/848085/58546599-9b140400-81fd-11e9-9c6b-23e708fdb997.gif)
